// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"slices"
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeCommand specifies the value command attribute.
type AttributeCommand int

const (
	_ AttributeCommand = iota
	AttributeCommandGet
	AttributeCommandSet
	AttributeCommandFlush
	AttributeCommandTouch
)

// String returns the string representation of the AttributeCommand.
func (av AttributeCommand) String() string {
	switch av {
	case AttributeCommandGet:
		return "get"
	case AttributeCommandSet:
		return "set"
	case AttributeCommandFlush:
		return "flush"
	case AttributeCommandTouch:
		return "touch"
	}
	return ""
}

// MapAttributeCommand is a helper map of string to AttributeCommand attribute value.
var MapAttributeCommand = map[string]AttributeCommand{
	"get":   AttributeCommandGet,
	"set":   AttributeCommandSet,
	"flush": AttributeCommandFlush,
	"touch": AttributeCommandTouch,
}

// AttributeDirection specifies the value direction attribute.
type AttributeDirection int

const (
	_ AttributeDirection = iota
	AttributeDirectionSent
	AttributeDirectionReceived
)

// String returns the string representation of the AttributeDirection.
func (av AttributeDirection) String() string {
	switch av {
	case AttributeDirectionSent:
		return "sent"
	case AttributeDirectionReceived:
		return "received"
	}
	return ""
}

// MapAttributeDirection is a helper map of string to AttributeDirection attribute value.
var MapAttributeDirection = map[string]AttributeDirection{
	"sent":     AttributeDirectionSent,
	"received": AttributeDirectionReceived,
}

// AttributeOperation specifies the value operation attribute.
type AttributeOperation int

const (
	_ AttributeOperation = iota
	AttributeOperationIncrement
	AttributeOperationDecrement
	AttributeOperationGet
)

// String returns the string representation of the AttributeOperation.
func (av AttributeOperation) String() string {
	switch av {
	case AttributeOperationIncrement:
		return "increment"
	case AttributeOperationDecrement:
		return "decrement"
	case AttributeOperationGet:
		return "get"
	}
	return ""
}

// MapAttributeOperation is a helper map of string to AttributeOperation attribute value.
var MapAttributeOperation = map[string]AttributeOperation{
	"increment": AttributeOperationIncrement,
	"decrement": AttributeOperationDecrement,
	"get":       AttributeOperationGet,
}

// AttributeSlabChunkState specifies the value slab_chunk_state attribute.
type AttributeSlabChunkState int

const (
	_ AttributeSlabChunkState = iota
	AttributeSlabChunkStateUsed
	AttributeSlabChunkStateFree
	AttributeSlabChunkStateTotal
)

// String returns the string representation of the AttributeSlabChunkState.
func (av AttributeSlabChunkState) String() string {
	switch av {
	case AttributeSlabChunkStateUsed:
		return "used"
	case AttributeSlabChunkStateFree:
		return "free"
	case AttributeSlabChunkStateTotal:
		return "total"
	}
	return ""
}

// MapAttributeSlabChunkState is a helper map of string to AttributeSlabChunkState attribute value.
var MapAttributeSlabChunkState = map[string]AttributeSlabChunkState{
	"used":  AttributeSlabChunkStateUsed,
	"free":  AttributeSlabChunkStateFree,
	"total": AttributeSlabChunkStateTotal,
}

// AttributeSlabOperation specifies the value slab_operation attribute.
type AttributeSlabOperation int

const (
	_ AttributeSlabOperation = iota
	AttributeSlabOperationSet
	AttributeSlabOperationGet
	AttributeSlabOperationDelete
	AttributeSlabOperationIncrement
	AttributeSlabOperationDecrement
	AttributeSlabOperationTouch
	AttributeSlabOperationCas
)

// String returns the string representation of the AttributeSlabOperation.
func (av AttributeSlabOperation) String() string {
	switch av {
	case AttributeSlabOperationSet:
		return "set"
	case AttributeSlabOperationGet:
		return "get"
	case AttributeSlabOperationDelete:
		return "delete"
	case AttributeSlabOperationIncrement:
		return "increment"
	case AttributeSlabOperationDecrement:
		return "decrement"
	case AttributeSlabOperationTouch:
		return "touch"
	case AttributeSlabOperationCas:
		return "cas"
	}
	return ""
}

// MapAttributeSlabOperation is a helper map of string to AttributeSlabOperation attribute value.
var MapAttributeSlabOperation = map[string]AttributeSlabOperation{
	"set":       AttributeSlabOperationSet,
	"get":       AttributeSlabOperationGet,
	"delete":    AttributeSlabOperationDelete,
	"increment": AttributeSlabOperationIncrement,
	"decrement": AttributeSlabOperationDecrement,
	"touch":     AttributeSlabOperationTouch,
	"cas":       AttributeSlabOperationCas,
}

// AttributeState specifies the value state attribute.
type AttributeState int

const (
	_ AttributeState = iota
	AttributeStateSystem
	AttributeStateUser
)

// String returns the string representation of the AttributeState.
func (av AttributeState) String() string {
	switch av {
	case AttributeStateSystem:
		return "system"
	case AttributeStateUser:
		return "user"
	}
	return ""
}

// MapAttributeState is a helper map of string to AttributeState attribute value.
var MapAttributeState = map[string]AttributeState{
	"system": AttributeStateSystem,
	"user":   AttributeStateUser,
}

// AttributeType specifies the value type attribute.
type AttributeType int

const (
	_ AttributeType = iota
	AttributeTypeHit
	AttributeTypeMiss
)

// String returns the string representation of the AttributeType.
func (av AttributeType) String() string {
	switch av {
	case AttributeTypeHit:
		return "hit"
	case AttributeTypeMiss:
		return "miss"
	}
	return ""
}

// MapAttributeType is a helper map of string to AttributeType attribute value.
var MapAttributeType = map[string]AttributeType{
	"hit":  AttributeTypeHit,
	"miss": AttributeTypeMiss,
}

var MetricsInfo = metricsInfo{
	MemcachedBytes: metricInfo{
		Name: "memcached.bytes",
	},
	MemcachedCommands: metricInfo{
		Name: "memcached.commands",
	},
	MemcachedConnectionsCurrent: metricInfo{
		Name: "memcached.connections.current",
	},
	MemcachedConnectionsTotal: metricInfo{
		Name: "memcached.connections.total",
	},
	MemcachedCPUUsage: metricInfo{
		Name: "memcached.cpu.usage",
	},
	MemcachedCurrentItems: metricInfo{
		Name: "memcached.current_items",
	},
	MemcachedEvictions: metricInfo{
		Name: "memcached.evictions",
	},
	MemcachedNetwork: metricInfo{
		Name: "memcached.network",
	},
	MemcachedOperationHitRatio: metricInfo{
		Name: "memcached.operation_hit_ratio",
	},
	MemcachedOperations: metricInfo{
		Name: "memcached.operations",
	},
	MemcachedSlabsAllocatedMemory: metricInfo{
		Name: "memcached.slabs.allocated_memory",
	},
	MemcachedSlabsChunkSize: metricInfo{
		Name: "memcached.slabs.chunk_size",
	},
	MemcachedSlabsChunks: metricInfo{
		Name: "memcached.slabs.chunks",
	},
	MemcachedSlabsChunksPerPage: metricInfo{
		Name: "memcached.slabs.chunks_per_page",
	},
	MemcachedSlabsCount: metricInfo{
		Name: "memcached.slabs.count",
	},
	MemcachedSlabsOperations: metricInfo{
		Name: "memcached.slabs.operations",
	},
	MemcachedSlabsPages: metricInfo{
		Name: "memcached.slabs.pages",
	},
	MemcachedSlabsRequestedMemory: metricInfo{
		Name: "memcached.slabs.requested_memory",
	},
	MemcachedThreads: metricInfo{
		Name: "memcached.threads",
	},
}

type metricsInfo struct {
	MemcachedBytes                metricInfo
	MemcachedCommands             metricInfo
	MemcachedConnectionsCurrent   metricInfo
	MemcachedConnectionsTotal     metricInfo
	MemcachedCPUUsage             metricInfo
	MemcachedCurrentItems         metricInfo
	MemcachedEvictions            metricInfo
	MemcachedNetwork              metricInfo
	MemcachedOperationHitRatio    metricInfo
	MemcachedOperations           metricInfo
	MemcachedSlabsAllocatedMemory metricInfo
	MemcachedSlabsChunkSize       metricInfo
	MemcachedSlabsChunks          metricInfo
	MemcachedSlabsChunksPerPage   metricInfo
	MemcachedSlabsCount           metricInfo
	MemcachedSlabsOperations      metricInfo
	MemcachedSlabsPages           metricInfo
	MemcachedSlabsRequestedMemory metricInfo
	MemcachedThreads              metricInfo
}

type metricInfo struct {
	Name string
}

type metricMemcachedBytes struct {
	data     pmetric.Metric             // data buffer for generated metric.
	config   MemcachedBytesMetricConfig // metric config provided by user.
	capacity int                        // max observed number of data points added to the metric.
}

// init fills memcached.bytes metric with initial data.
func (m *metricMemcachedBytes) init() {
	m.data.SetName("memcached.bytes")
	m.data.SetDescription("Current number of bytes used by this server to store items.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricMemcachedBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedBytes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedBytes(cfg MemcachedBytesMetricConfig) metricMemcachedBytes {
	m := metricMemcachedBytes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedCommands struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        MemcachedCommandsMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills memcached.commands metric with initial data.
func (m *metricMemcachedCommands) init() {
	m.data.SetName("memcached.commands")
	m.data.SetDescription("Commands executed.")
	m.data.SetUnit("{commands}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedCommands) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, commandAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedCommandsMetricAttributeKeyCommand) {
		dp.Attributes().PutStr("command", commandAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedCommands) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedCommands) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedCommands(cfg MemcachedCommandsMetricConfig) metricMemcachedCommands {
	m := metricMemcachedCommands{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedConnectionsCurrent struct {
	data     pmetric.Metric                          // data buffer for generated metric.
	config   MemcachedConnectionsCurrentMetricConfig // metric config provided by user.
	capacity int                                     // max observed number of data points added to the metric.
}

// init fills memcached.connections.current metric with initial data.
func (m *metricMemcachedConnectionsCurrent) init() {
	m.data.SetName("memcached.connections.current")
	m.data.SetDescription("The current number of open connections.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricMemcachedConnectionsCurrent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedConnectionsCurrent) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedConnectionsCurrent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedConnectionsCurrent(cfg MemcachedConnectionsCurrentMetricConfig) metricMemcachedConnectionsCurrent {
	m := metricMemcachedConnectionsCurrent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedConnectionsTotal struct {
	data     pmetric.Metric                        // data buffer for generated metric.
	config   MemcachedConnectionsTotalMetricConfig // metric config provided by user.
	capacity int                                   // max observed number of data points added to the metric.
}

// init fills memcached.connections.total metric with initial data.
func (m *metricMemcachedConnectionsTotal) init() {
	m.data.SetName("memcached.connections.total")
	m.data.SetDescription("Total number of connections opened since the server started running.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricMemcachedConnectionsTotal) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedConnectionsTotal) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedConnectionsTotal) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedConnectionsTotal(cfg MemcachedConnectionsTotalMetricConfig) metricMemcachedConnectionsTotal {
	m := metricMemcachedConnectionsTotal{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedCPUUsage struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        MemcachedCPUUsageMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []float64                     // slice containing number of aggregated datapoints at each index
}

// init fills memcached.cpu.usage metric with initial data.
func (m *metricMemcachedCPUUsage) init() {
	m.data.SetName("memcached.cpu.usage")
	m.data.SetDescription("Accumulated user and system time.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedCPUUsage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, stateAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedCPUUsageMetricAttributeKeyState) {
		dp.Attributes().PutStr("state", stateAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedCPUUsage) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedCPUUsage) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetDoubleValue(m.data.Sum().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedCPUUsage(cfg MemcachedCPUUsageMetricConfig) metricMemcachedCPUUsage {
	m := metricMemcachedCPUUsage{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedCurrentItems struct {
	data     pmetric.Metric                    // data buffer for generated metric.
	config   MemcachedCurrentItemsMetricConfig // metric config provided by user.
	capacity int                               // max observed number of data points added to the metric.
}

// init fills memcached.current_items metric with initial data.
func (m *metricMemcachedCurrentItems) init() {
	m.data.SetName("memcached.current_items")
	m.data.SetDescription("Number of items currently stored in the cache.")
	m.data.SetUnit("{items}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricMemcachedCurrentItems) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedCurrentItems) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedCurrentItems) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedCurrentItems(cfg MemcachedCurrentItemsMetricConfig) metricMemcachedCurrentItems {
	m := metricMemcachedCurrentItems{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedEvictions struct {
	data     pmetric.Metric                 // data buffer for generated metric.
	config   MemcachedEvictionsMetricConfig // metric config provided by user.
	capacity int                            // max observed number of data points added to the metric.
}

// init fills memcached.evictions metric with initial data.
func (m *metricMemcachedEvictions) init() {
	m.data.SetName("memcached.evictions")
	m.data.SetDescription("Cache item evictions.")
	m.data.SetUnit("{evictions}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricMemcachedEvictions) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedEvictions) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedEvictions) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedEvictions(cfg MemcachedEvictionsMetricConfig) metricMemcachedEvictions {
	m := metricMemcachedEvictions{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedNetwork struct {
	data          pmetric.Metric               // data buffer for generated metric.
	config        MemcachedNetworkMetricConfig // metric config provided by user.
	capacity      int                          // max observed number of data points added to the metric.
	aggDataPoints []int64                      // slice containing number of aggregated datapoints at each index
}

// init fills memcached.network metric with initial data.
func (m *metricMemcachedNetwork) init() {
	m.data.SetName("memcached.network")
	m.data.SetDescription("Bytes transferred over the network.")
	m.data.SetUnit("by")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedNetwork) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, directionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedNetworkMetricAttributeKeyDirection) {
		dp.Attributes().PutStr("direction", directionAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedNetwork) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedNetwork) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedNetwork(cfg MemcachedNetworkMetricConfig) metricMemcachedNetwork {
	m := metricMemcachedNetwork{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedOperationHitRatio struct {
	data          pmetric.Metric                         // data buffer for generated metric.
	config        MemcachedOperationHitRatioMetricConfig // metric config provided by user.
	capacity      int                                    // max observed number of data points added to the metric.
	aggDataPoints []float64                              // slice containing number of aggregated datapoints at each index
}

// init fills memcached.operation_hit_ratio metric with initial data.
func (m *metricMemcachedOperationHitRatio) init() {
	m.data.SetName("memcached.operation_hit_ratio")
	m.data.SetDescription("Hit ratio for operations, expressed as a percentage value between 0.0 and 100.0.")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedOperationHitRatio) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedOperationHitRatioMetricAttributeKeyOperation) {
		dp.Attributes().PutStr("operation", operationAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedOperationHitRatio) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedOperationHitRatio) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedOperationHitRatio(cfg MemcachedOperationHitRatioMetricConfig) metricMemcachedOperationHitRatio {
	m := metricMemcachedOperationHitRatio{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedOperations struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        MemcachedOperationsMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []int64                         // slice containing number of aggregated datapoints at each index
}

// init fills memcached.operations metric with initial data.
func (m *metricMemcachedOperations) init() {
	m.data.SetName("memcached.operations")
	m.data.SetDescription("Operation counts.")
	m.data.SetUnit("{operations}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedOperations) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, typeAttributeValue string, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedOperationsMetricAttributeKeyType) {
		dp.Attributes().PutStr("type", typeAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, MemcachedOperationsMetricAttributeKeyOperation) {
		dp.Attributes().PutStr("operation", operationAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedOperations) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedOperations) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedOperations(cfg MemcachedOperationsMetricConfig) metricMemcachedOperations {
	m := metricMemcachedOperations{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsAllocatedMemory struct {
	data     pmetric.Metric                            // data buffer for generated metric.
	config   MemcachedSlabsAllocatedMemoryMetricConfig // metric config provided by user.
	capacity int                                       // max observed number of data points added to the metric.
}

// init fills memcached.slabs.allocated_memory metric with initial data.
func (m *metricMemcachedSlabsAllocatedMemory) init() {
	m.data.SetName("memcached.slabs.allocated_memory")
	m.data.SetDescription("Total memory allocated to slab pages.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricMemcachedSlabsAllocatedMemory) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsAllocatedMemory) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsAllocatedMemory) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsAllocatedMemory(cfg MemcachedSlabsAllocatedMemoryMetricConfig) metricMemcachedSlabsAllocatedMemory {
	m := metricMemcachedSlabsAllocatedMemory{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsChunkSize struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        MemcachedSlabsChunkSizeMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills memcached.slabs.chunk_size metric with initial data.
func (m *metricMemcachedSlabsChunkSize) init() {
	m.data.SetName("memcached.slabs.chunk_size")
	m.data.SetDescription("The amount of space each chunk uses in a slab class.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedSlabsChunkSize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsChunkSizeMetricAttributeKeySlab) {
		dp.Attributes().PutInt("slab", slabAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsChunkSize) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsChunkSize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsChunkSize(cfg MemcachedSlabsChunkSizeMetricConfig) metricMemcachedSlabsChunkSize {
	m := metricMemcachedSlabsChunkSize{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsChunks struct {
	data          pmetric.Metric                   // data buffer for generated metric.
	config        MemcachedSlabsChunksMetricConfig // metric config provided by user.
	capacity      int                              // max observed number of data points added to the metric.
	aggDataPoints []int64                          // slice containing number of aggregated datapoints at each index
}

// init fills memcached.slabs.chunks metric with initial data.
func (m *metricMemcachedSlabsChunks) init() {
	m.data.SetName("memcached.slabs.chunks")
	m.data.SetDescription("Number of chunks in a slab class, by allocation state.")
	m.data.SetUnit("{chunk}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedSlabsChunks) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, slabAttributeValue int64, slabChunkStateAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsChunksMetricAttributeKeySlab) {
		dp.Attributes().PutInt("slab", slabAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsChunksMetricAttributeKeySlabChunkState) {
		dp.Attributes().PutStr("slab_chunk_state", slabChunkStateAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsChunks) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsChunks) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsChunks(cfg MemcachedSlabsChunksMetricConfig) metricMemcachedSlabsChunks {
	m := metricMemcachedSlabsChunks{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsChunksPerPage struct {
	data          pmetric.Metric                          // data buffer for generated metric.
	config        MemcachedSlabsChunksPerPageMetricConfig // metric config provided by user.
	capacity      int                                     // max observed number of data points added to the metric.
	aggDataPoints []int64                                 // slice containing number of aggregated datapoints at each index
}

// init fills memcached.slabs.chunks_per_page metric with initial data.
func (m *metricMemcachedSlabsChunksPerPage) init() {
	m.data.SetName("memcached.slabs.chunks_per_page")
	m.data.SetDescription("Number of chunks within a single page in a slab class.")
	m.data.SetUnit("{chunk}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedSlabsChunksPerPage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsChunksPerPageMetricAttributeKeySlab) {
		dp.Attributes().PutInt("slab", slabAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsChunksPerPage) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsChunksPerPage) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsChunksPerPage(cfg MemcachedSlabsChunksPerPageMetricConfig) metricMemcachedSlabsChunksPerPage {
	m := metricMemcachedSlabsChunksPerPage{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsCount struct {
	data     pmetric.Metric                  // data buffer for generated metric.
	config   MemcachedSlabsCountMetricConfig // metric config provided by user.
	capacity int                             // max observed number of data points added to the metric.
}

// init fills memcached.slabs.count metric with initial data.
func (m *metricMemcachedSlabsCount) init() {
	m.data.SetName("memcached.slabs.count")
	m.data.SetDescription("Total number of slab classes allocated.")
	m.data.SetUnit("{slab}")
	m.data.SetEmptyGauge()
}

func (m *metricMemcachedSlabsCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsCount(cfg MemcachedSlabsCountMetricConfig) metricMemcachedSlabsCount {
	m := metricMemcachedSlabsCount{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsOperations struct {
	data          pmetric.Metric                       // data buffer for generated metric.
	config        MemcachedSlabsOperationsMetricConfig // metric config provided by user.
	capacity      int                                  // max observed number of data points added to the metric.
	aggDataPoints []int64                              // slice containing number of aggregated datapoints at each index
}

// init fills memcached.slabs.operations metric with initial data.
func (m *metricMemcachedSlabsOperations) init() {
	m.data.SetName("memcached.slabs.operations")
	m.data.SetDescription("Number of operations serviced by a slab class.")
	m.data.SetUnit("{operation}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedSlabsOperations) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, slabAttributeValue int64, slabOperationAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsOperationsMetricAttributeKeySlab) {
		dp.Attributes().PutInt("slab", slabAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsOperationsMetricAttributeKeySlabOperation) {
		dp.Attributes().PutStr("slab_operation", slabOperationAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsOperations) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsOperations) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsOperations(cfg MemcachedSlabsOperationsMetricConfig) metricMemcachedSlabsOperations {
	m := metricMemcachedSlabsOperations{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsPages struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        MemcachedSlabsPagesMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []int64                         // slice containing number of aggregated datapoints at each index
}

// init fills memcached.slabs.pages metric with initial data.
func (m *metricMemcachedSlabsPages) init() {
	m.data.SetName("memcached.slabs.pages")
	m.data.SetDescription("Total number of pages allocated to a slab class.")
	m.data.SetUnit("{page}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedSlabsPages) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsPagesMetricAttributeKeySlab) {
		dp.Attributes().PutInt("slab", slabAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsPages) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsPages) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsPages(cfg MemcachedSlabsPagesMetricConfig) metricMemcachedSlabsPages {
	m := metricMemcachedSlabsPages{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedSlabsRequestedMemory struct {
	data          pmetric.Metric                            // data buffer for generated metric.
	config        MemcachedSlabsRequestedMemoryMetricConfig // metric config provided by user.
	capacity      int                                       // max observed number of data points added to the metric.
	aggDataPoints []int64                                   // slice containing number of aggregated datapoints at each index
}

// init fills memcached.slabs.requested_memory metric with initial data.
func (m *metricMemcachedSlabsRequestedMemory) init() {
	m.data.SetName("memcached.slabs.requested_memory")
	m.data.SetDescription("Number of bytes requested to be stored in a slab class.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricMemcachedSlabsRequestedMemory) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, MemcachedSlabsRequestedMemoryMetricAttributeKeySlab) {
		dp.Attributes().PutInt("slab", slabAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedSlabsRequestedMemory) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedSlabsRequestedMemory) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedSlabsRequestedMemory(cfg MemcachedSlabsRequestedMemoryMetricConfig) metricMemcachedSlabsRequestedMemory {
	m := metricMemcachedSlabsRequestedMemory{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricMemcachedThreads struct {
	data     pmetric.Metric               // data buffer for generated metric.
	config   MemcachedThreadsMetricConfig // metric config provided by user.
	capacity int                          // max observed number of data points added to the metric.
}

// init fills memcached.threads metric with initial data.
func (m *metricMemcachedThreads) init() {
	m.data.SetName("memcached.threads")
	m.data.SetDescription("Number of threads used by the memcached instance.")
	m.data.SetUnit("{threads}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricMemcachedThreads) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricMemcachedThreads) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricMemcachedThreads) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricMemcachedThreads(cfg MemcachedThreadsMetricConfig) metricMemcachedThreads {
	m := metricMemcachedThreads{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                              MetricsBuilderConfig // config of the metrics builder.
	startTime                           pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                     int                  // maximum observed number of metrics per resource.
	metricsBuffer                       pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                           component.BuildInfo  // contains version information.
	metricMemcachedBytes                metricMemcachedBytes
	metricMemcachedCommands             metricMemcachedCommands
	metricMemcachedConnectionsCurrent   metricMemcachedConnectionsCurrent
	metricMemcachedConnectionsTotal     metricMemcachedConnectionsTotal
	metricMemcachedCPUUsage             metricMemcachedCPUUsage
	metricMemcachedCurrentItems         metricMemcachedCurrentItems
	metricMemcachedEvictions            metricMemcachedEvictions
	metricMemcachedNetwork              metricMemcachedNetwork
	metricMemcachedOperationHitRatio    metricMemcachedOperationHitRatio
	metricMemcachedOperations           metricMemcachedOperations
	metricMemcachedSlabsAllocatedMemory metricMemcachedSlabsAllocatedMemory
	metricMemcachedSlabsChunkSize       metricMemcachedSlabsChunkSize
	metricMemcachedSlabsChunks          metricMemcachedSlabsChunks
	metricMemcachedSlabsChunksPerPage   metricMemcachedSlabsChunksPerPage
	metricMemcachedSlabsCount           metricMemcachedSlabsCount
	metricMemcachedSlabsOperations      metricMemcachedSlabsOperations
	metricMemcachedSlabsPages           metricMemcachedSlabsPages
	metricMemcachedSlabsRequestedMemory metricMemcachedSlabsRequestedMemory
	metricMemcachedThreads              metricMemcachedThreads
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                              mbc,
		startTime:                           pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                       pmetric.NewMetrics(),
		buildInfo:                           settings.BuildInfo,
		metricMemcachedBytes:                newMetricMemcachedBytes(mbc.Metrics.MemcachedBytes),
		metricMemcachedCommands:             newMetricMemcachedCommands(mbc.Metrics.MemcachedCommands),
		metricMemcachedConnectionsCurrent:   newMetricMemcachedConnectionsCurrent(mbc.Metrics.MemcachedConnectionsCurrent),
		metricMemcachedConnectionsTotal:     newMetricMemcachedConnectionsTotal(mbc.Metrics.MemcachedConnectionsTotal),
		metricMemcachedCPUUsage:             newMetricMemcachedCPUUsage(mbc.Metrics.MemcachedCPUUsage),
		metricMemcachedCurrentItems:         newMetricMemcachedCurrentItems(mbc.Metrics.MemcachedCurrentItems),
		metricMemcachedEvictions:            newMetricMemcachedEvictions(mbc.Metrics.MemcachedEvictions),
		metricMemcachedNetwork:              newMetricMemcachedNetwork(mbc.Metrics.MemcachedNetwork),
		metricMemcachedOperationHitRatio:    newMetricMemcachedOperationHitRatio(mbc.Metrics.MemcachedOperationHitRatio),
		metricMemcachedOperations:           newMetricMemcachedOperations(mbc.Metrics.MemcachedOperations),
		metricMemcachedSlabsAllocatedMemory: newMetricMemcachedSlabsAllocatedMemory(mbc.Metrics.MemcachedSlabsAllocatedMemory),
		metricMemcachedSlabsChunkSize:       newMetricMemcachedSlabsChunkSize(mbc.Metrics.MemcachedSlabsChunkSize),
		metricMemcachedSlabsChunks:          newMetricMemcachedSlabsChunks(mbc.Metrics.MemcachedSlabsChunks),
		metricMemcachedSlabsChunksPerPage:   newMetricMemcachedSlabsChunksPerPage(mbc.Metrics.MemcachedSlabsChunksPerPage),
		metricMemcachedSlabsCount:           newMetricMemcachedSlabsCount(mbc.Metrics.MemcachedSlabsCount),
		metricMemcachedSlabsOperations:      newMetricMemcachedSlabsOperations(mbc.Metrics.MemcachedSlabsOperations),
		metricMemcachedSlabsPages:           newMetricMemcachedSlabsPages(mbc.Metrics.MemcachedSlabsPages),
		metricMemcachedSlabsRequestedMemory: newMetricMemcachedSlabsRequestedMemory(mbc.Metrics.MemcachedSlabsRequestedMemory),
		metricMemcachedThreads:              newMetricMemcachedThreads(mbc.Metrics.MemcachedThreads),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricMemcachedBytes.emit(ils.Metrics())
	mb.metricMemcachedCommands.emit(ils.Metrics())
	mb.metricMemcachedConnectionsCurrent.emit(ils.Metrics())
	mb.metricMemcachedConnectionsTotal.emit(ils.Metrics())
	mb.metricMemcachedCPUUsage.emit(ils.Metrics())
	mb.metricMemcachedCurrentItems.emit(ils.Metrics())
	mb.metricMemcachedEvictions.emit(ils.Metrics())
	mb.metricMemcachedNetwork.emit(ils.Metrics())
	mb.metricMemcachedOperationHitRatio.emit(ils.Metrics())
	mb.metricMemcachedOperations.emit(ils.Metrics())
	mb.metricMemcachedSlabsAllocatedMemory.emit(ils.Metrics())
	mb.metricMemcachedSlabsChunkSize.emit(ils.Metrics())
	mb.metricMemcachedSlabsChunks.emit(ils.Metrics())
	mb.metricMemcachedSlabsChunksPerPage.emit(ils.Metrics())
	mb.metricMemcachedSlabsCount.emit(ils.Metrics())
	mb.metricMemcachedSlabsOperations.emit(ils.Metrics())
	mb.metricMemcachedSlabsPages.emit(ils.Metrics())
	mb.metricMemcachedSlabsRequestedMemory.emit(ils.Metrics())
	mb.metricMemcachedThreads.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordMemcachedBytesDataPoint adds a data point to memcached.bytes metric.
func (mb *MetricsBuilder) RecordMemcachedBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedCommandsDataPoint adds a data point to memcached.commands metric.
func (mb *MetricsBuilder) RecordMemcachedCommandsDataPoint(ts pcommon.Timestamp, val int64, commandAttributeValue AttributeCommand) {
	mb.metricMemcachedCommands.recordDataPoint(mb.startTime, ts, val, commandAttributeValue.String())
}

// RecordMemcachedConnectionsCurrentDataPoint adds a data point to memcached.connections.current metric.
func (mb *MetricsBuilder) RecordMemcachedConnectionsCurrentDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedConnectionsCurrent.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedConnectionsTotalDataPoint adds a data point to memcached.connections.total metric.
func (mb *MetricsBuilder) RecordMemcachedConnectionsTotalDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedConnectionsTotal.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedCPUUsageDataPoint adds a data point to memcached.cpu.usage metric.
func (mb *MetricsBuilder) RecordMemcachedCPUUsageDataPoint(ts pcommon.Timestamp, val float64, stateAttributeValue AttributeState) {
	mb.metricMemcachedCPUUsage.recordDataPoint(mb.startTime, ts, val, stateAttributeValue.String())
}

// RecordMemcachedCurrentItemsDataPoint adds a data point to memcached.current_items metric.
func (mb *MetricsBuilder) RecordMemcachedCurrentItemsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedCurrentItems.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedEvictionsDataPoint adds a data point to memcached.evictions metric.
func (mb *MetricsBuilder) RecordMemcachedEvictionsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedEvictions.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedNetworkDataPoint adds a data point to memcached.network metric.
func (mb *MetricsBuilder) RecordMemcachedNetworkDataPoint(ts pcommon.Timestamp, val int64, directionAttributeValue AttributeDirection) {
	mb.metricMemcachedNetwork.recordDataPoint(mb.startTime, ts, val, directionAttributeValue.String())
}

// RecordMemcachedOperationHitRatioDataPoint adds a data point to memcached.operation_hit_ratio metric.
func (mb *MetricsBuilder) RecordMemcachedOperationHitRatioDataPoint(ts pcommon.Timestamp, val float64, operationAttributeValue AttributeOperation) {
	mb.metricMemcachedOperationHitRatio.recordDataPoint(mb.startTime, ts, val, operationAttributeValue.String())
}

// RecordMemcachedOperationsDataPoint adds a data point to memcached.operations metric.
func (mb *MetricsBuilder) RecordMemcachedOperationsDataPoint(ts pcommon.Timestamp, val int64, typeAttributeValue AttributeType, operationAttributeValue AttributeOperation) {
	mb.metricMemcachedOperations.recordDataPoint(mb.startTime, ts, val, typeAttributeValue.String(), operationAttributeValue.String())
}

// RecordMemcachedSlabsAllocatedMemoryDataPoint adds a data point to memcached.slabs.allocated_memory metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsAllocatedMemoryDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedSlabsAllocatedMemory.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedSlabsChunkSizeDataPoint adds a data point to memcached.slabs.chunk_size metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsChunkSizeDataPoint(ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	mb.metricMemcachedSlabsChunkSize.recordDataPoint(mb.startTime, ts, val, slabAttributeValue)
}

// RecordMemcachedSlabsChunksDataPoint adds a data point to memcached.slabs.chunks metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsChunksDataPoint(ts pcommon.Timestamp, val int64, slabAttributeValue int64, slabChunkStateAttributeValue AttributeSlabChunkState) {
	mb.metricMemcachedSlabsChunks.recordDataPoint(mb.startTime, ts, val, slabAttributeValue, slabChunkStateAttributeValue.String())
}

// RecordMemcachedSlabsChunksPerPageDataPoint adds a data point to memcached.slabs.chunks_per_page metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsChunksPerPageDataPoint(ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	mb.metricMemcachedSlabsChunksPerPage.recordDataPoint(mb.startTime, ts, val, slabAttributeValue)
}

// RecordMemcachedSlabsCountDataPoint adds a data point to memcached.slabs.count metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsCountDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedSlabsCount.recordDataPoint(mb.startTime, ts, val)
}

// RecordMemcachedSlabsOperationsDataPoint adds a data point to memcached.slabs.operations metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsOperationsDataPoint(ts pcommon.Timestamp, val int64, slabAttributeValue int64, slabOperationAttributeValue AttributeSlabOperation) {
	mb.metricMemcachedSlabsOperations.recordDataPoint(mb.startTime, ts, val, slabAttributeValue, slabOperationAttributeValue.String())
}

// RecordMemcachedSlabsPagesDataPoint adds a data point to memcached.slabs.pages metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsPagesDataPoint(ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	mb.metricMemcachedSlabsPages.recordDataPoint(mb.startTime, ts, val, slabAttributeValue)
}

// RecordMemcachedSlabsRequestedMemoryDataPoint adds a data point to memcached.slabs.requested_memory metric.
func (mb *MetricsBuilder) RecordMemcachedSlabsRequestedMemoryDataPoint(ts pcommon.Timestamp, val int64, slabAttributeValue int64) {
	mb.metricMemcachedSlabsRequestedMemory.recordDataPoint(mb.startTime, ts, val, slabAttributeValue)
}

// RecordMemcachedThreadsDataPoint adds a data point to memcached.threads metric.
func (mb *MetricsBuilder) RecordMemcachedThreadsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricMemcachedThreads.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
