// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					MemcachedBytes: MemcachedBytesMetricConfig{
						Enabled: true,
					},
					MemcachedCommands: MemcachedCommandsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedCommandsMetricAttributeKey{MemcachedCommandsMetricAttributeKeyCommand},
					},
					MemcachedConnectionsCurrent: MemcachedConnectionsCurrentMetricConfig{
						Enabled: true,
					},
					MemcachedConnectionsTotal: MemcachedConnectionsTotalMetricConfig{
						Enabled: true,
					},
					MemcachedCPUUsage: MemcachedCPUUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedCPUUsageMetricAttributeKey{MemcachedCPUUsageMetricAttributeKeyState},
					},
					MemcachedCurrentItems: MemcachedCurrentItemsMetricConfig{
						Enabled: true,
					},
					MemcachedEvictions: MemcachedEvictionsMetricConfig{
						Enabled: true,
					},
					MemcachedNetwork: MemcachedNetworkMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedNetworkMetricAttributeKey{MemcachedNetworkMetricAttributeKeyDirection},
					},
					MemcachedOperationHitRatio: MemcachedOperationHitRatioMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedOperationHitRatioMetricAttributeKey{MemcachedOperationHitRatioMetricAttributeKeyOperation},
					},
					MemcachedOperations: MemcachedOperationsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedOperationsMetricAttributeKey{MemcachedOperationsMetricAttributeKeyType, MemcachedOperationsMetricAttributeKeyOperation},
					},
					MemcachedSlabsAllocatedMemory: MemcachedSlabsAllocatedMemoryMetricConfig{
						Enabled: true,
					},
					MemcachedSlabsChunkSize: MemcachedSlabsChunkSizeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsChunkSizeMetricAttributeKey{MemcachedSlabsChunkSizeMetricAttributeKeySlab},
					},
					MemcachedSlabsChunks: MemcachedSlabsChunksMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsChunksMetricAttributeKey{MemcachedSlabsChunksMetricAttributeKeySlab, MemcachedSlabsChunksMetricAttributeKeySlabChunkState},
					},
					MemcachedSlabsChunksPerPage: MemcachedSlabsChunksPerPageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsChunksPerPageMetricAttributeKey{MemcachedSlabsChunksPerPageMetricAttributeKeySlab},
					},
					MemcachedSlabsCount: MemcachedSlabsCountMetricConfig{
						Enabled: true,
					},
					MemcachedSlabsOperations: MemcachedSlabsOperationsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedSlabsOperationsMetricAttributeKey{MemcachedSlabsOperationsMetricAttributeKeySlab, MemcachedSlabsOperationsMetricAttributeKeySlabOperation},
					},
					MemcachedSlabsPages: MemcachedSlabsPagesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsPagesMetricAttributeKey{MemcachedSlabsPagesMetricAttributeKeySlab},
					},
					MemcachedSlabsRequestedMemory: MemcachedSlabsRequestedMemoryMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsRequestedMemoryMetricAttributeKey{MemcachedSlabsRequestedMemoryMetricAttributeKeySlab},
					},
					MemcachedThreads: MemcachedThreadsMetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					MemcachedBytes: MemcachedBytesMetricConfig{
						Enabled: false,
					},
					MemcachedCommands: MemcachedCommandsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedCommandsMetricAttributeKey{MemcachedCommandsMetricAttributeKeyCommand},
					},
					MemcachedConnectionsCurrent: MemcachedConnectionsCurrentMetricConfig{
						Enabled: false,
					},
					MemcachedConnectionsTotal: MemcachedConnectionsTotalMetricConfig{
						Enabled: false,
					},
					MemcachedCPUUsage: MemcachedCPUUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedCPUUsageMetricAttributeKey{MemcachedCPUUsageMetricAttributeKeyState},
					},
					MemcachedCurrentItems: MemcachedCurrentItemsMetricConfig{
						Enabled: false,
					},
					MemcachedEvictions: MemcachedEvictionsMetricConfig{
						Enabled: false,
					},
					MemcachedNetwork: MemcachedNetworkMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedNetworkMetricAttributeKey{MemcachedNetworkMetricAttributeKeyDirection},
					},
					MemcachedOperationHitRatio: MemcachedOperationHitRatioMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedOperationHitRatioMetricAttributeKey{MemcachedOperationHitRatioMetricAttributeKeyOperation},
					},
					MemcachedOperations: MemcachedOperationsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedOperationsMetricAttributeKey{MemcachedOperationsMetricAttributeKeyType, MemcachedOperationsMetricAttributeKeyOperation},
					},
					MemcachedSlabsAllocatedMemory: MemcachedSlabsAllocatedMemoryMetricConfig{
						Enabled: false,
					},
					MemcachedSlabsChunkSize: MemcachedSlabsChunkSizeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsChunkSizeMetricAttributeKey{MemcachedSlabsChunkSizeMetricAttributeKeySlab},
					},
					MemcachedSlabsChunks: MemcachedSlabsChunksMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsChunksMetricAttributeKey{MemcachedSlabsChunksMetricAttributeKeySlab, MemcachedSlabsChunksMetricAttributeKeySlabChunkState},
					},
					MemcachedSlabsChunksPerPage: MemcachedSlabsChunksPerPageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsChunksPerPageMetricAttributeKey{MemcachedSlabsChunksPerPageMetricAttributeKeySlab},
					},
					MemcachedSlabsCount: MemcachedSlabsCountMetricConfig{
						Enabled: false,
					},
					MemcachedSlabsOperations: MemcachedSlabsOperationsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MemcachedSlabsOperationsMetricAttributeKey{MemcachedSlabsOperationsMetricAttributeKeySlab, MemcachedSlabsOperationsMetricAttributeKeySlabOperation},
					},
					MemcachedSlabsPages: MemcachedSlabsPagesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsPagesMetricAttributeKey{MemcachedSlabsPagesMetricAttributeKeySlab},
					},
					MemcachedSlabsRequestedMemory: MemcachedSlabsRequestedMemoryMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []MemcachedSlabsRequestedMemoryMetricAttributeKey{MemcachedSlabsRequestedMemoryMetricAttributeKeySlab},
					},
					MemcachedThreads: MemcachedThreadsMetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MemcachedBytesMetricConfig{}, MemcachedCommandsMetricConfig{}, MemcachedConnectionsCurrentMetricConfig{}, MemcachedConnectionsTotalMetricConfig{}, MemcachedCPUUsageMetricConfig{}, MemcachedCurrentItemsMetricConfig{}, MemcachedEvictionsMetricConfig{}, MemcachedNetworkMetricConfig{}, MemcachedOperationHitRatioMetricConfig{}, MemcachedOperationsMetricConfig{}, MemcachedSlabsAllocatedMemoryMetricConfig{}, MemcachedSlabsChunkSizeMetricConfig{}, MemcachedSlabsChunksMetricConfig{}, MemcachedSlabsChunksPerPageMetricConfig{}, MemcachedSlabsCountMetricConfig{}, MemcachedSlabsOperationsMetricConfig{}, MemcachedSlabsPagesMetricConfig{}, MemcachedSlabsRequestedMemoryMetricConfig{}, MemcachedThreadsMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
